//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoCompressorGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoCompressorGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About compri.
        /// </summary>
        public static string AboutCompri {
            get {
                return ResourceManager.GetString("AboutCompri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compri is an interface between FFmpeg and a simple usablity. Our goal is to simplify the editing of media.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After compression.
        /// </summary>
        public static string AfterCompression {
            get {
                return ResourceManager.GetString("AfterCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the target size.
        /// </summary>
        public static string CalculateTargetSize {
            get {
                return ResourceManager.GetString("CalculateTargetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        public static string Compress {
            get {
                return ResourceManager.GetString("Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the list item after compression.
        /// </summary>
        public static string DeleteListItemAfterCompression {
            get {
                return ResourceManager.GetString("DeleteListItemAfterCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the file after compression.
        /// </summary>
        public static string DeleteOriginalAfterCompression {
            get {
                return ResourceManager.GetString("DeleteOriginalAfterCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this element from the list.
        /// </summary>
        public static string DeleteThisElement {
            get {
                return ResourceManager.GetString("DeleteThisElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digit required.
        /// </summary>
        public static string DigitRequired {
            get {
                return ResourceManager.GetString("DigitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digit too long.
        /// </summary>
        public static string DigitTooLong {
            get {
                return ResourceManager.GetString("DigitTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloadability.
        /// </summary>
        public static string Downloadability {
            get {
                return ResourceManager.GetString("Downloadability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadFFmpeg to this path.
        /// </summary>
        public static string DownloadFFmpegHere {
            get {
                return ResourceManager.GetString("DownloadFFmpegHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit presets.
        /// </summary>
        public static string EditPresets {
            get {
                return ResourceManager.GetString("EditPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a filename.
        /// </summary>
        public static string EnterFilename {
            get {
                return ResourceManager.GetString("EnterFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg could not be loaded.
        /// </summary>
        public static string FFmpegCouldntBeLoaded {
            get {
                return ResourceManager.GetString("FFmpegCouldntBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ending.
        /// </summary>
        public static string FileEnding {
            get {
                return ResourceManager.GetString("FileEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following file is missing.
        /// </summary>
        public static string FollowingFileMissing {
            get {
                return ResourceManager.GetString("FollowingFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following files are missing.
        /// </summary>
        public static string FollowingFilesMissing {
            get {
                return ResourceManager.GetString("FollowingFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames / Second.
        /// </summary>
        public static string FramesPerSecond {
            get {
                return ResourceManager.GetString("FramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root directory.
        /// </summary>
        public static string HighestDirectory {
            get {
                return ResourceManager.GetString("HighestDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case there is no path, the standard directory will be the same as the original file&apos;s directory.
        /// </summary>
        public static string InCaseNoPath {
            get {
                return ResourceManager.GetString("InCaseNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last compression options.
        /// </summary>
        public static string LastCompressOptions {
            get {
                return ResourceManager.GetString("LastCompressOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use.
        /// </summary>
        public static string NameAlreadyUsed {
            get {
                return ResourceManager.GetString("NameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the preset.
        /// </summary>
        public static string NameOfPreset {
            get {
                return ResourceManager.GetString("NameOfPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name too long.
        /// </summary>
        public static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new video automatically.
        /// </summary>
        public static string NewestVideos {
            get {
                return ResourceManager.GetString("NewestVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not supported.
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no update available.
        /// </summary>
        public static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video selected.
        /// </summary>
        public static string NoVideoSelected {
            get {
                return ResourceManager.GetString("NoVideoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only digits.
        /// </summary>
        public static string OnlyDigits {
            get {
                return ResourceManager.GetString("OnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Explorer after compression.
        /// </summary>
        public static string OpenExplorerAfterCompression {
            get {
                return ResourceManager.GetString("OpenExplorerAfterCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Explorer after the last compression in the list.
        /// </summary>
        public static string OpenExplorerAfterLastCompression {
            get {
                return ResourceManager.GetString("OpenExplorerAfterLastCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this element in explorer.
        /// </summary>
        public static string OpenThisElementInExplorer {
            get {
                return ResourceManager.GetString("OpenThisElementInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or search here.
        /// </summary>
        public static string OrSearchHere {
            get {
                return ResourceManager.GetString("OrSearchHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path rules.
        /// </summary>
        public static string Pathrules {
            get {
                return ResourceManager.GetString("Pathrules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playbackspeed.
        /// </summary>
        public static string Playbackspeed {
            get {
                return ResourceManager.GetString("Playbackspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined bitrate.
        /// </summary>
        public static string PredefinedBitrate {
            get {
                return ResourceManager.GetString("PredefinedBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set when compressing.
        /// </summary>
        public static string SetDuringCompress {
            get {
                return ResourceManager.GetString("SetDuringCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the thumbnail of the rear sliding element.
        /// </summary>
        public static string ShowThumbnail {
            get {
                return ResourceManager.GetString("ShowThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard case for the pathrules in the compress dialog.
        /// </summary>
        public static string StandardcaseForRules {
            get {
                return ResourceManager.GetString("StandardcaseForRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory.
        /// </summary>
        public static string TargetDirectory {
            get {
                return ResourceManager.GetString("TargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File&apos;s target size.
        /// </summary>
        public static string TargetsizeOfFile {
            get {
                return ResourceManager.GetString("TargetsizeOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute update (Restart required).
        /// </summary>
        public static string UpdateAndRestart {
            get {
                return ResourceManager.GetString("UpdateAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined cases.
        /// </summary>
        public static string UserDefinedCases {
            get {
                return ResourceManager.GetString("UserDefinedCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videobrowser list item.
        /// </summary>
        public static string VideoBrowserListItem {
            get {
                return ResourceManager.GetString("VideoBrowserListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videoinformation.
        /// </summary>
        public static string Videoinformation {
            get {
                return ResourceManager.GetString("Videoinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string WannaContinue {
            get {
                return ResourceManager.GetString("WannaContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to delete all red marked cells, because they are incorrect.
        /// </summary>
        public static string YoureAboutRedCells {
            get {
                return ResourceManager.GetString("YoureAboutRedCells", resourceCulture);
            }
        }
    }
}
